export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/',
  PR: {
    ROOT: '/pr',
    CREATE: '/pr/create',
    STATUS: '/pr/status',
    HISTORY: '/pr/history',
    DETAIL: '/pr/:id',
  },
  PO: {
    ROOT: '/po',
    CREATE: '/po/create',
    STATUS: '/po/status',
    HISTORY: '/po/history',
    DETAIL: '/po/:id',
  },
  MEMO: {
    ROOT: '/memo',
    LIST: '/memo',
    CREATE: '/memo/create',
    DETAIL: '/memo/:id',
    EDIT: '/memo/:id/edit',
    APPROVAL: '/memo/approval',
    APPROVAL_DETAIL: '/memo/:id/approval-detail',
  },
  MASTER: {
    ROOT: '/master',
    GROUPS: '/master/groups',
    MATERIALS: '/master/materials',
    COST_CODE: '/master/cost-code',
    LOCATION: '/master/location',
    SUPPLIER: '/master/supplier',
    STOCK: '/master/stock',
    PROJECTS: '/master/projects',
    PROJECTS_CREATE: '/master/projects/create',
    PROJECTS_EDIT: '/master/projects/:id/edit',
  },
  SYSTEM: {
    ROOT: '/system',
    CONFIG: '/system/config',
    USERS: '/system/users',
    ROLES: '/system/roles',
    MENUS: '/system/menus',
    PERMISSIONS: '/system/permissions',
  },
  ADMIN: {
    ROOT: '/admin',
    APPROVAL_MATRIX: '/admin/approval-matrix',
    PERMISSION_MATRIX: '/admin/permission-matrix',
  },
  STOCK: {
    ITEMS:           '/stock/items',
    ITEMS_CREATE:    '/stock/items/create',
    ITEMS_EDIT:      '/stock/items/:id/edit',
    INVENTORY:       '/stock/inventory',
    TRANSACTIONS:    '/stock/transactions',
    BORROW:          '/stock/borrow',
    BORROW_CREATE:   '/stock/borrow/create',
    BORROW_DETAIL:   '/stock/borrow/:id',
    BORROW_APPROVAL: '/stock/borrow/approval',
    RESERVATIONS:    '/stock/reservations',
    QRCODE:          '/stock/qrcode',
    RECEIVING:         '/stock/receiving',
    RECEIVING_DETAIL:  '/stock/receiving/:poId',
    RECEIVING_HISTORY: '/stock/receiving/history',
    REQUISITION:        '/stock/requisition',
    REQUISITION_CREATE: '/stock/requisition/create',
    REQUISITION_EDIT:   '/stock/requisition/:id/edit',
    REQUISITION_DETAIL: '/stock/requisition/:id',
  },
} as const
