export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/',
  PR: {
    ROOT: '/pr',
    CREATE: '/pr/create',
    STATUS: '/pr/status',
    HISTORY: '/pr/history',
    DETAIL: '/pr/:id',
  },
  PO: {
    ROOT: '/po',
    CREATE: '/po/create',
    STATUS: '/po/status',
    HISTORY: '/po/history',
    DETAIL: '/po/:id',
  },
  MEMO: {
    ROOT: '/memo',
    LIST: '/memo',
    CREATE: '/memo/create',
    DETAIL: '/memo/:id',
    EDIT: '/memo/:id/edit',
    APPROVAL: '/memo/approval',
    APPROVAL_DETAIL: '/memo/:id/approval-detail',
  },
  MASTER: {
    ROOT: '/master',
    GROUPS: '/master/groups',
    MATERIALS: '/master/materials',
    LOCATION: '/master/location',
    SUPPLIER: '/master/supplier',
  },
  SYSTEM: {
    ROOT: '/system',
    CONFIG: '/system/config',
    USERS: '/system/users',
    ROLES: '/system/roles',
    MENUS: '/system/menus',
    PERMISSIONS: '/system/permissions',
  },
  ADMIN: {
    ROOT: '/admin',
    APPROVAL_MATRIX: '/admin/approval-matrix',
    PERMISSION_MATRIX: '/admin/permission-matrix',
  },
} as const
