import type { PurchaseRequest, PurchaseOrder, Memo } from '@/types'

export const MOCK_PR_LIST: PurchaseRequest[] = [
  {
    id: 'pr-001',
    prNumber: 'PR-2024-0001',
    title: 'ซื้อวัสดุสำนักงาน',
    requester: 'สมชาย ใจดี',
    department: 'IT',
    status: 'pending',
    priority: 'medium',
    requestDate: '2024-09-01',
    requiredDate: '2024-09-15',
    totalAmount: 15000,
    items: [
      { id: 'i1', description: 'กระดาษ A4', quantity: 10, unit: 'รีม', estimatedPrice: 500 },
      { id: 'i2', description: 'ปากกาลูกลื่น', quantity: 50, unit: 'ด้าม', estimatedPrice: 20 },
    ],
  },
  {
    id: 'pr-002',
    prNumber: 'PR-2024-0002',
    title: 'ซื้ออุปกรณ์คอมพิวเตอร์',
    requester: 'สมหญิง รักดี',
    department: 'HR',
    status: 'approved',
    priority: 'high',
    requestDate: '2024-09-02',
    requiredDate: '2024-09-10',
    totalAmount: 85000,
    items: [
      { id: 'i3', description: 'RAM 16GB', quantity: 5, unit: 'ชิ้น', estimatedPrice: 2500 },
    ],
    approver: 'ผู้จัดการ',
    approvedDate: '2024-09-03',
  },
  {
    id: 'pr-003',
    prNumber: 'PR-2024-0003',
    title: 'ซื้อวัสดุทำความสะอาด',
    requester: 'มานะ ขยันดี',
    department: 'OPS',
    status: 'draft',
    priority: 'low',
    requestDate: '2024-09-03',
    requiredDate: '2024-09-20',
    totalAmount: 5000,
    items: [],
  },
  {
    id: 'pr-004',
    prNumber: 'PR-2024-0004',
    title: 'ซื้อเฟอร์นิเจอร์สำนักงาน',
    requester: 'สุดา ดีใจ',
    department: 'FIN',
    status: 'rejected',
    priority: 'urgent',
    requestDate: '2024-09-04',
    requiredDate: '2024-09-12',
    totalAmount: 120000,
    items: [],
    remarks: 'งบประมาณเกิน',
  },
]

export const MOCK_PO_LIST: PurchaseOrder[] = [
  {
    id: 'po-001',
    poNumber: 'PO-2024-0001',
    prId: 'pr-002',
    vendor: 'บริษัท ABC จำกัด',
    status: 'sent',
    orderDate: '2024-09-05',
    deliveryDate: '2024-09-15',
    totalAmount: 85000,
    createdBy: 'admin',
    items: [
      { id: 'pi1', description: 'RAM 16GB', quantity: 5, unit: 'ชิ้น', unitPrice: 2500, totalPrice: 12500 },
    ],
  },
  {
    id: 'po-002',
    poNumber: 'PO-2024-0002',
    vendor: 'บริษัท XYZ จำกัด',
    status: 'partial',
    orderDate: '2024-09-06',
    deliveryDate: '2024-09-20',
    totalAmount: 42000,
    createdBy: 'admin',
    items: [],
  },
  {
    id: 'po-003',
    poNumber: 'PO-2024-0003',
    vendor: 'ห้างหุ้นส่วน DEF',
    status: 'completed',
    orderDate: '2024-09-01',
    deliveryDate: '2024-09-05',
    totalAmount: 15000,
    createdBy: 'manager',
    items: [],
  },
]

export const mockMemos: Memo[] = [
  {
    id: 'memo-001',
    memoNo: 'MEM-2506-0042',
    title: 'วัสดุเดินสายไฟฟ้าชั้น 2 อาคาร B',
    projectName: 'ติดตั้งระบบไฟฟ้า Zone B',
    supplierName: 'บ. สยามวัสดุ จำกัด',
    requestedBy: 'สมชาย ใจดี',
    requestedById: 'user-005',
    department: 'แผนกก่อสร้าง',
    note: 'ต้องการวัสดุสำหรับงานเดินสายไฟฟ้าชั้น 2 อาคาร B ตามแบบแปลน Rev.3',
    items: [
      { id: 'mi-001', description: 'สายไฟ THW 2.5 Sq.mm. สีแดง (ม้วนละ 100 ม.)', unit: 'ม้วน', quantity: 5, estimatedPrice: 1200, remark: 'ยี่ห้อ Yazaki' },
      { id: 'mi-002', description: 'ท่อ EMT 3/4" พร้อมอุปกรณ์ประกอบ', unit: 'เส้น', quantity: 30, estimatedPrice: 180 },
      { id: 'mi-003', description: 'กล่องพักสายสี่เหลี่ยม 4"×4"', unit: 'ใบ', quantity: 20, estimatedPrice: 45 },
      { id: 'mi-004', description: 'สวิตช์ไฟ 2 ทาง ยี่ห้อ Panasonic', unit: 'ชิ้น', quantity: 10, estimatedPrice: 220, remark: 'แนะนำร้าน A' },
    ],
    totalAmount: 13150,
    status: 'pending_po',
    linkedPoIds: [],
    createdAt: '2025-06-23T09:00:00Z',
    updatedAt: '2025-06-23T09:00:00Z',
  },
  {
    id: 'memo-002',
    memoNo: 'MEM-2506-0041',
    title: 'อุปกรณ์ PPE ประจำเดือน มิ.ย.',
    projectName: 'งานบำรุงรักษาทั่วไป',
    requestedBy: 'วิภา รักดี',
    requestedById: 'user-007',
    department: 'แผนก Safety',
    note: 'ต้องการเพิ่มสต็อก PPE ประจำเดือน',
    items: [
      { id: 'mi-005', description: 'หมวกนิรภัย สีเหลือง มอก.', unit: 'ใบ', quantity: 20, estimatedPrice: 150 },
      { id: 'mi-006', description: 'รองเท้านิรภัย Safety Jogger S3', unit: 'คู่', quantity: 10, estimatedPrice: 1800 },
      { id: 'mi-007', description: 'ถุงมือหนัง ป้องกันการตัด', unit: 'คู่', quantity: 50, estimatedPrice: 85 },
    ],
    totalAmount: 25250,
    status: 'po_created',
    linkedPoIds: ['po-099'],
    createdAt: '2025-06-20T14:30:00Z',
    updatedAt: '2025-06-21T10:00:00Z',
  },
  {
    id: 'memo-003',
    memoNo: 'MEM-2506-0038',
    title: 'น้ำมันหล่อลื่นงานซ่อมบำรุง PM Q2',
    projectName: 'PM ประจำไตรมาส Q2',
    requestedBy: 'สุรชัย แก้วใส',
    requestedById: 'user-003',
    department: 'แผนกซ่อมบำรุง',
    items: [
      { id: 'mi-008', description: 'น้ำมันเครื่อง Shell Rimula R4 15W-40', unit: 'ถัง', quantity: 4, estimatedPrice: 2200 },
      { id: 'mi-009', description: 'จาระบี Molykote EM-30L', unit: 'กก.', quantity: 5, estimatedPrice: 650 },
    ],
    totalAmount: 12050,
    status: 'draft',
    linkedPoIds: [],
    createdAt: '2025-06-18T08:15:00Z',
    updatedAt: '2025-06-18T08:15:00Z',
  },
]
