import type { StockItem, StockInventory, BorrowRequest, Reservation } from '@/types/stock'

export const mockStockItems: StockItem[] = [
  {
    id: 1,
    itemCode: 'STK-001',
    itemName: 'Electric Drill',
    description: 'Cordless electric drill 18V',
    itemType: 'returnable',
    trackingType: 'sku',
    unit: 'EA',
    minQty: 2,
    categoryId: 1,
    categoryName: 'Tools',
    qrCode: 'STK-001',
    isActive: true,
    createdAt: '2024-01-10T08:00:00Z',
    updatedAt: '2024-01-10T08:00:00Z',
  },
  {
    id: 2,
    itemCode: 'STK-002',
    itemName: 'Safety Helmet',
    description: 'Hard hat ANSI Z89.1',
    itemType: 'returnable',
    trackingType: 'sku',
    unit: 'EA',
    minQty: 5,
    categoryId: 2,
    categoryName: 'Safety Equipment',
    qrCode: 'STK-002',
    isActive: true,
    createdAt: '2024-01-10T08:00:00Z',
    updatedAt: '2024-01-10T08:00:00Z',
  },
  {
    id: 3,
    itemCode: 'STK-003',
    itemName: 'Cleaning Solvent',
    description: 'Industrial cleaning solvent 5L',
    itemType: 'consumable',
    trackingType: 'sku',
    unit: 'BOT',
    minQty: 10,
    categoryId: 3,
    categoryName: 'Consumables',
    qrCode: 'STK-003',
    isActive: true,
    createdAt: '2024-01-10T08:00:00Z',
    updatedAt: '2024-01-10T08:00:00Z',
  },
  {
    id: 4,
    itemCode: 'STK-004',
    itemName: 'Measuring Tape 5m',
    description: 'Steel measuring tape 5 meter',
    itemType: 'returnable',
    trackingType: 'sku',
    unit: 'EA',
    minQty: 3,
    categoryId: 1,
    categoryName: 'Tools',
    qrCode: 'STK-004',
    isActive: true,
    createdAt: '2024-01-12T08:00:00Z',
    updatedAt: '2024-01-12T08:00:00Z',
  },
  {
    id: 5,
    itemCode: 'STK-005',
    itemName: 'Cable Tie Pack',
    description: 'Cable ties 200mm pack of 100',
    itemType: 'consumable',
    trackingType: 'sku',
    unit: 'PACK',
    minQty: 20,
    categoryId: 3,
    categoryName: 'Consumables',
    qrCode: 'STK-005',
    isActive: false,
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-01-15T08:00:00Z',
  },
]

export const mockInventory: StockInventory[] = [
  { id: 1, itemId: 1, itemCode: 'STK-001', itemName: 'Electric Drill',    unit: 'EA',   locationId: 1, locationName: 'Warehouse A - Zone 1', warehouseCode: 'WH-A', qtyOnHand: 5,  qtyReserved: 1, qtyAvailable: 4 },
  { id: 2, itemId: 1, itemCode: 'STK-001', itemName: 'Electric Drill',    unit: 'EA',   locationId: 2, locationName: 'Warehouse B - Zone 1', warehouseCode: 'WH-B', qtyOnHand: 2,  qtyReserved: 0, qtyAvailable: 2 },
  { id: 3, itemId: 2, itemCode: 'STK-002', itemName: 'Safety Helmet',     unit: 'EA',   locationId: 1, locationName: 'Warehouse A - Zone 1', warehouseCode: 'WH-A', qtyOnHand: 3,  qtyReserved: 1, qtyAvailable: 2 },
  { id: 4, itemId: 3, itemCode: 'STK-003', itemName: 'Cleaning Solvent',  unit: 'BOT',  locationId: 1, locationName: 'Warehouse A - Zone 2', warehouseCode: 'WH-A', qtyOnHand: 8,  qtyReserved: 0, qtyAvailable: 8 },
  { id: 5, itemId: 4, itemCode: 'STK-004', itemName: 'Measuring Tape 5m', unit: 'EA',   locationId: 2, locationName: 'Warehouse B - Zone 1', warehouseCode: 'WH-B', qtyOnHand: 0,  qtyReserved: 0, qtyAvailable: 0 },
  { id: 6, itemId: 5, itemCode: 'STK-005', itemName: 'Cable Tie Pack',    unit: 'PACK', locationId: 1, locationName: 'Warehouse A - Zone 2', warehouseCode: 'WH-A', qtyOnHand: 15, qtyReserved: 5, qtyAvailable: 10 },
]

export const mockBorrowRequests: BorrowRequest[] = [
  {
    id: 1,
    borrowNo: 'BRW-2024-001',
    status: 'BORROWED',
    requestedBy: 'John Doe',
    requestedById: 1,
    approvedBy: 'Manager A',
    purpose: 'Site inspection tools',
    borrowDate: '2024-06-01',
    expectedReturnDate: '2024-06-10',
    lines: [
      { id: 1, borrowId: 1, lineNo: 1, itemId: 1, itemCode: 'STK-001', itemName: 'Electric Drill', locationId: 1, locationName: 'Warehouse A - Zone 1', qtyRequested: 2, qtyApproved: 2, qtyBorrowed: 2, qtyReturned: 0, unit: 'EA' },
    ],
    createdAt: '2024-06-01T08:00:00Z',
  },
  {
    id: 2,
    borrowNo: 'BRW-2024-002',
    status: 'PENDING_APPROVAL',
    requestedBy: 'Jane Smith',
    requestedById: 2,
    purpose: 'Maintenance work',
    borrowDate: '2024-06-15',
    expectedReturnDate: '2024-06-20',
    lines: [
      { id: 2, borrowId: 2, lineNo: 1, itemId: 2, itemCode: 'STK-002', itemName: 'Safety Helmet', locationId: 1, locationName: 'Warehouse A - Zone 1', qtyRequested: 3, unit: 'EA' },
    ],
    createdAt: '2024-06-14T08:00:00Z',
  },
  {
    id: 3,
    borrowNo: 'BRW-2024-003',
    status: 'RETURNED',
    requestedBy: 'Bob Wilson',
    requestedById: 3,
    approvedBy: 'Manager A',
    purpose: 'Equipment testing',
    borrowDate: '2024-05-20',
    expectedReturnDate: '2024-05-25',
    actualReturnDate: '2024-05-24',
    lines: [
      { id: 3, borrowId: 3, lineNo: 1, itemId: 4, itemCode: 'STK-004', itemName: 'Measuring Tape 5m', locationId: 2, locationName: 'Warehouse B - Zone 1', qtyRequested: 2, qtyApproved: 2, qtyBorrowed: 2, qtyReturned: 2, unit: 'EA' },
    ],
    createdAt: '2024-05-19T08:00:00Z',
  },
  {
    id: 4,
    borrowNo: 'BRW-2024-004',
    status: 'DRAFT',
    requestedBy: 'Alice Lee',
    requestedById: 4,
    purpose: 'Project A setup',
    borrowDate: '2024-06-20',
    lines: [],
    createdAt: '2024-06-18T08:00:00Z',
  },
]

export const mockReservations: Reservation[] = [
  {
    id: 1,
    reservationNo: 'RSV-2024-001',
    status: 'CONFIRMED',
    itemId: 1,
    itemCode: 'STK-001',
    itemName: 'Electric Drill',
    locationId: 1,
    locationName: 'Warehouse A - Zone 1',
    qtyReserved: 1,
    requestedBy: 'Project Team A',
    neededBy: '2024-07-01',
    purpose: 'Project installation',
    createdAt: '2024-06-10T08:00:00Z',
  },
  {
    id: 2,
    reservationNo: 'RSV-2024-002',
    status: 'PENDING',
    itemId: 2,
    itemCode: 'STK-002',
    itemName: 'Safety Helmet',
    locationId: 1,
    locationName: 'Warehouse A - Zone 1',
    qtyReserved: 1,
    requestedBy: 'Safety Team',
    neededBy: '2024-06-30',
    purpose: 'New staff onboarding',
    createdAt: '2024-06-12T08:00:00Z',
  },
]
